### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by pawitp** [pawitp/protobuf-decoder#1]
We need a README that
- Links to the production site
- Explain the goal of the project
- Include example data to play around with and a screenshot
- Explain how to run the project (`yarn` && `yarn start`)

**Comment by pawitp** [comment]
Fixed by #7

**Comment by axilis-marko** [comment]
I think it would be useful to add the source data of the example in README.md. Perhaps the data in JSON format and proto schema that defines it. What currently confuses me is the double `1` as field number where it's type was `string` but it had more proto content in it.
