### ISSUE TITLE
UI: Large protos get cut off

### ISSUE THREAD

**Issue by Iscle** [pawitp/protobuf-decoder#62]
When analyzing large protos, they get cut off when they don't fit on the screen, and the X-axis scrolling is disabled because in CSS "overflow-x" is set to "hidden" for the body.

Disabling it in chrome dev tools will make it work correctly.

![Screenshot from 2023-05-11 14-30-44](https://github.com/pawitp/protobuf-decoder/assets/8018823/cde03c79-6247-494d-8af8-5d7038d1f55d)

I'm guessing the option will need to be added as "visible" in the page's css.

**Comment by pawitp** [comment]
Do you have example data I can use to reproduce the issue?

**Comment by pawitp** [comment]
I think it got fixed in #61
