### ISSUE TITLE
horizontal scroll ball isn't showing in the website. 

### ISSUE THREAD

**Issue by Vishnuksekar** [pawitp/protobuf-decoder#63]

**Comment by Vishnuksekar** [comment]
Hi there,

there isn't horizontal scroll in the UI, which crops the decoded content.

**Comment by pawitp** [comment]
Please share sample protobuf and screenshot

**Comment by Iscle** [comment]
This is the same as #62, but the issue was not appearing anymore for me...

**Comment by pawitp** [comment]
I'll close this for now. Please re-open if you can reproduce the issue.
