### ISSUE TITLE
Site note found, use Github CI?

### ISSUE THREAD

**Issue by konsumer** [pawitp/protobuf-decoder#88]
Seeing "site not found" at [netlify](https://protobuf-decoder.netlify.com/). Could this be related to my tooling PR? #87 

It seems to show up fine on [the preview](https://deploy-preview-87--protobuf-decoder.netlify.app/) so I am not really sure where else to look for the issue. Maybe it just needs a redeploy?

Related sidenote, I could set this up as a github action, and host on github pages, instead.

They provide free hosting, and it would link the logs in the action panel, so it might be a bit easier to troubleshoot, for people like me, that do not have access to the netlify-panel. I bet CircleCI stuff could be done in Actions, too...

**Comment by konsumer** [comment]
I setup some rudimentary github actions [here](https://github.com/konsumer/protobuf-decoder/actions/runs/8904309160/job/24453396714) I can PR for, if you are interested. It doesn't gate on coverage (which I find dubious in many situations, anyway) but runs test on all pushes, and deploys pages on `master`.

**Comment by konsumer** [comment]
I added a github secret for `CODECOV_TOKEN` and now it shows up:

<img width="1347" alt="Screenshot 2024-04-30 at 8 28 40 PM" src="https://github.com/pawitp/protobuf-decoder/assets/83857/d5799975-0a07-45a5-a787-be44af0d58d2">

So, I think that is all that is needed.

**Comment by pawitp** [comment]
Looks like Netlify removed their `netlify.com` domain for applications.

https://answers.netlify.com/t/deprecating-automatic-com-redirects/115442/2
