### ISSUE TITLE
Link to netlify app broken

### ISSUE THREAD

**Issue by StefSchenkelaars** [pawitp/protobuf-decoder#95]
On the GitHub page the link to the app has the `.com` extension while it should be `.app`:
![image](https://github.com/user-attachments/assets/7517f118-1862-42a5-a5f7-6c4bb5571bee)

I don't have permissions to fix it so it would be great if @pawitp could change that 😃

**Comment by pawitp** [comment]
Thanks for pointing this out. Fixed.
